---
- name: Check if SSL config is there
  stat: path="/etc/nginx/snippets/{{ app_nginx_ssl_snippet }}.ssl.conf"
  register: app_nginx_ssl_config_file

- name: Check if acme_well_known config is there
  stat: path="/etc/nginx/snippets/acme_well_known.conf"
  register: app_nginx_ssl_acme_well_known_config_file

- name: Ensure app Nginx config present
  template:
    src: templates/nginx_app.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ app_name }}.conf"
  notify:
     - nginx reload
